<a href="https://colab.research.google.com/github/mithunkumarsr/LearnPythonWithMithun/blob/master/LVC_8_Python_Numpy_MCA_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy



---


**Content:**


1.  Introduction to Numpy

2.   Creating Arrays

1.  Array Indexing

2.   Array Slicing

1.   Array Shape and Reshape

2.   Array Iterating

1.   Array Joining and Spliting

2.   Array Search, Sort and Filter

1.   Random Introduction

2.   ufunc Introduction

1.   ufunc_Finding LCM and GCD

2.   ufunc_Set Operations




---




**NumPy** is a general-purpose array-processing package.
 It provides a high-performance multidimensional array object, and tools for working with these arrays.

  It is the fundamental package for scientific computing with Python.
  It is open-source software.
   It contains various features including these important ones:


*   A powerful N-dimensional array object
*   Sophisticated (broadcasting) functions

*   Tools for integrating C/C++ and Fortran code
*   Useful linear algebra, Fourier transform, and random number capabilities




**Using Numpy Arrays**

The main reason to use **NumPy** is that it

*   **provides a high-performance** alternative to Python's built-in lists.
*   NumPy arrays are more efficient than lists in terms of **memory usage and computation time**.

*   **NumPy arrays are optimized for numerical computations** and are implemented in low-level languages like **C and Fortran**, while lists in Python are implemented in pure Python.
*   **NumPy is faster** than lists because of its implementation in low-level languages and the use of vectorized operations.



*   **Vectorized operations** allow for operations on entire arrays without the need for explicit looping.
*   NumPy is written in the **C programming language**.





In [3]:
#pip install numpy
import numpy as np

**Creation Numpy**

In [4]:
mylist=[1,2,3,4]
print(mylist)
print(type(mylist))

[1, 2, 3, 4]
<class 'list'>


In [5]:
#converson from list object to n dimensional Array
np.array(mylist)
print("Array Elements are:   ", mylist)
print("Type of mylist variable is:  ", type(mylist))


Array Elements are:    [1, 2, 3, 4]
Type of mylist variable is:   <class 'list'>


np.arange is a function in the NumPy library that generates a ndarray (i.e., a N-dimensional array) with evenly spaced values within a given range. The syntax for using np.arange is as follows:

np.arange(start, stop, step, dtype)


where:


1.   **start (optional)** is the starting value of the sequence. The default value is 0.
2.   **stop** is the ending value of the sequence. This value is not included in the generated array.

1.  **step (optional)** is the difference between each value in the sequence. The default value is 1.
2.   **dtype (optional)** is the data type of the elements in the generated array. The default value is float.



In [6]:
print(np.arange(0,11,1))
print(np.arange(0,11,2))

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  2  4  6  8 10]


In [7]:
np.zeros(3)

array([0., 0., 0.])

In [8]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [10]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [12]:
np.linspace(0,10,21)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [13]:
#identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

np.random.rand is a function in the NumPy library that generates random numbers from a uniform distribution. The rand function generates an array of specified shape filled with random values between 0 and 1.

The syntax for using np.random.rand is as follows:
***np.random.rand(d0, d1, ..., dn)***


For example, if you want to generate a 1-dimensional array with 2 random numbers, you can use the following code:



In [14]:
np.random.rand(2)

array([0.65061776, 0.40428228])

In [15]:
#uniform distribution
np.random.rand(3,4)

array([[0.44150063, 0.37519042, 0.34994333, 0.63053611],
       [0.58335052, 0.8066006 , 0.68504127, 0.50584443],
       [0.08896547, 0.64803036, 0.80940794, 0.63299684]])

The function **np.random.randn**generates random numbers from the "standard normal" distribution (mean of 0 and standard deviation of 1).

In [16]:
# norma distribution
np.random.randn(5,5)

array([[ 2.20921676, -1.48178736, -1.12821825, -1.36011839,  0.27578423],
       [-0.90676452, -0.75640734,  0.00633167,  0.67013896, -1.63018109],
       [-0.32023366,  1.9970305 , -0.19935119, -1.53810686, -0.65892686],
       [-0.69672701,  0.01585583,  1.64228542, -1.61722749,  0.12893627],
       [-0.3960038 ,  1.18953366, -0.43964067,  0.72383551, -1.11984121]])

**numpy.random.randint** is a function in the NumPy library that generates random integers between a specified low and high value (inclusive).

`random.randint(low, high=None, size=None,` `dtype=int)`


Return random integers from low (inclusive) to high (exclusive)



*   low: The low end of the interval (inclusive). This parameter is required.
*   high: The high end of the interval (exclusive). If high is not specified, low will be taken as the high value and low as 0.

*   size: The shape of the output array. If size is not specified, a single integer will be generated.
dtype: The data type of the output array.int








In [17]:
np.random.randint(1,100)

37

In [18]:
np.random.randint(1,100, 5)

array([60,  1, 94,  1, 10])

In [22]:
np.random.randint(1,100, (2,3))

array([[83, 87, 75],
       [75, 88, 24]])

In [21]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [23]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [24]:
import numpy as np

# Seed the random number generator with 42
np.random.seed(25)

# Generate random numbers with shape (3, 3)
random_numbers_1 = np.random.rand(3, 3)
print(random_numbers_1)

# Output:
# [[0.37454012 0.95071431 0.73199394]
#  [0.59865848 0.15601864 0.15599452]
#  [0.05808361 0.86617615 0.60111501]]
print("Again with same seed value")
# Run the code again

# Seed the random number generator with 42
np.random.seed(25)

# Generate random numbers with shape (3, 3)
random_numbers_2 = np.random.rand(3, 3)
print(random_numbers_2)

# Output:
# [[0.37454012 0.95071431 0.73199394]
#  [0.59865848 0.15601864 0.15599452]
#  [0.05808361 0.86617615 0.60111501]]


[[0.87012414 0.58227693 0.27883894]
 [0.18591123 0.41110013 0.11737555]
 [0.68496874 0.43761106 0.55622933]]
Again with same seed value
[[0.87012414 0.58227693 0.27883894]
 [0.18591123 0.41110013 0.11737555]
 [0.68496874 0.43761106 0.55622933]]


In [25]:
# Python program to demonstrate
# basic array characteristics
import numpy as np

# Creating array object
arr = np.array( [[ 1, 2, 3],
				[ 4, 2, 5]] )

# Printing type of arr object
print("Array is of type: ", type(arr))

# Printing array dimensions (axes)
print("No. of dimensions: ", arr.ndim)

# Printing shape of array
print("Shape of array: ", arr.shape)

# Printing size (total number of elements) of array
print("Size of array: ", arr.size)

# Printing type of elements in array
print("Array stores elements of type: ", arr.dtype)


Array is of type:  <class 'numpy.ndarray'>
No. of dimensions:  2
Shape of array:  (2, 3)
Size of array:  6
Array stores elements of type:  int64


In [26]:
# Python program to demonstrate
# array creation techniques
import numpy as np

# Creating array from list with type float
a = np.array([[1, 2, 4], [5, 8, 7]], dtype = 'float')
print ("Array created using passed list:\n", a)

# Creating array from tuple
b = np.array((1 , 3, 2))
print ("\nArray created using passed tuple:\n", b)

# Creating a 3X4 array with all zeros
c = np.zeros((3, 4))
print ("\nAn array initialized with all zeros:\n", c)

# Create a constant value array of complex type
d = np.full((3, 3), 6, dtype = 'complex')
print ("\nAn array initialized with all 6s."
			"Array type is complex:\n", d)

# Create an array with random values
e = np.random.random((2, 2))
print ("\nA random array:\n", e)

# Create a sequence of integers
# from 0 to 30 with steps of 5
f = np.arange(0, 30, 5)
print ("\nA sequential array with steps of 5:\n", f)

# Create a sequence of 10 values in range 0 to 5
g = np.linspace(0, 5, 10)
print ("\nA sequential array with 10 values between"
										"0 and 5:\n", g)

# Reshaping 3X4 array to 2X2X3 array
arr = np.array([[1, 2, 3, 4],
				[5, 2, 4, 2],
				[1, 2, 0, 1]])

newarr = arr.reshape(2, 2, 3)

print ("\nOriginal array:\n", arr)
print ("Reshaped array:\n", newarr)

# Flatten array
arr = np.array([[1, 2, 3], [4, 5, 6]])
flarr = arr.flatten()

print ("\nOriginal array:\n", arr)
print ("Fattened array:\n", flarr)


Array created using passed list:
 [[1. 2. 4.]
 [5. 8. 7.]]

Array created using passed tuple:
 [1 3 2]

An array initialized with all zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

An array initialized with all 6s.Array type is complex:
 [[6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]]

A random array:
 [[0.36708032 0.40236573]
 [0.1130407  0.44703085]]

A sequential array with steps of 5:
 [ 0  5 10 15 20 25]

A sequential array with 10 values between0 and 5:
 [0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]

Original array:
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]
Reshaped array:
 [[[1 2 3]
  [4 5 2]]

 [[4 2 1]
  [2 0 1]]]

Original array:
 [[1 2 3]
 [4 5 6]]
Fattened array:
 [1 2 3 4 5 6]


**Numpy Builtin functions and attributes**

**Reshape**

In [27]:
arr=np.random.randint(1,100,6)
print("arr", arr)

randarr=np.random.rand(25)
print("randarr", randarr)

arr [46  4  2 23 32 49]
randarr [0.32605113 0.69918624 0.36639455 0.83637451 0.48134294 0.5165023
 0.38304813 0.9975409  0.51424449 0.55905327 0.03444977 0.71993003
 0.42100355 0.43693513 0.28170075 0.90027434 0.66961228 0.45606875
 0.28980434 0.52581896 0.55924206 0.74528383 0.82834625 0.82369445
 0.07714032]


In [28]:
print(arr.shape)
print(randarr.shape)

(6,)
(25,)


In [29]:
randarr.reshape(5,5)
#randarr.reshape(6,3)

array([[0.32605113, 0.69918624, 0.36639455, 0.83637451, 0.48134294],
       [0.5165023 , 0.38304813, 0.9975409 , 0.51424449, 0.55905327],
       [0.03444977, 0.71993003, 0.42100355, 0.43693513, 0.28170075],
       [0.90027434, 0.66961228, 0.45606875, 0.28980434, 0.52581896],
       [0.55924206, 0.74528383, 0.82834625, 0.82369445, 0.07714032]])

In [30]:
# Maximum value
arr.max()

49

In [31]:
# Minimum value
arr.min()

2

In [32]:
# index number of maximum argument
arr.argmax()

5

In [33]:
# Minimum value
arr.argmin()

2

**Numpy Indexing and selection**

In [34]:
#Grabiing Single Element
arr=np.arange(0,11)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [35]:
print(arr[8])# Single element
print(arr[1:5])
print(arr[0:5])
print(arr[:])



8
[1 2 3 4]
[0 1 2 3 4]
[ 0  1  2  3  4  5  6  7  8  9 10]


In [36]:
print(arr[:-1])

[0 1 2 3 4 5 6 7 8 9]


**Broadcasting**

In [37]:
arr[0:5]=100
print(arr)

[100 100 100 100 100   5   6   7   8   9  10]


In [38]:
slice_of_array=arr[0:5]
slice_of_array[:]=99
print(slice_of_array)

[99 99 99 99 99]


In [39]:
print(arr)

[99 99 99 99 99  5  6  7  8  9 10]


In [40]:
arr_copy=arr.copy()
arr_copy[:]=99
print(arr_copy)

[99 99 99 99 99 99 99 99 99 99 99]


In [41]:
print(arr)

[99 99 99 99 99  5  6  7  8  9 10]


Indexing on 2D array

In [42]:
import numpy as np
arr_2d=np.array([[1,2,3], [4,5,6], [7,8,9]])

In [43]:
print(arr_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [44]:
arr_2d.shape

(3, 3)

In [45]:
arr_2d[0]

array([1, 2, 3])

In [46]:
arr_2d[2]

array([7, 8, 9])

In [47]:
arr_2d[2][0]

7

In [48]:
arr_2d[:,0]

array([1, 4, 7])

In [49]:
arr_2d[:,1:3]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [51]:
arr_2d[0:2,1:3]

array([[2, 3],
       [5, 6]])

In [52]:
# Python program to demonstrate
# indexing in numpy
import numpy as np

# An exemplar array
arr = np.array([[-1, 2, 0, 4],
				[4, -0.5, 6, 0],
				[2.6, 0, 7, 8],
				[3, -7, 4, 2.0]])

# Slicing array
temp = arr[:2, ::2]
print ("Array with first 2 rows and alternate"
					"columns(0 and 2):\n", temp)

# Integer array indexing example
temp = arr[[0, 1, 2, 3], [3, 2, 1, 0]]
print ("\nElements at indices (0, 3), (1, 2), (2, 1),"
									"(3, 0):\n", temp)

# boolean array indexing example
cond = arr > 0 # cond is a boolean array
temp = arr[cond]
print ("\nElements greater than 0:\n", temp)


Array with first 2 rows and alternatecolumns(0 and 2):
 [[-1.  0.]
 [ 4.  6.]]

Elements at indices (0, 3), (1, 2), (2, 1),(3, 0):
 [4. 6. 0. 3.]

Elements greater than 0:
 [2.  4.  4.  6.  2.6 7.  8.  3.  4.  2. ]


**Conditional selection**

In [53]:
import numpy as np
arr=np.arange(1,11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [54]:
arr>4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [55]:
bool_arr=arr>4
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [56]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

**NumPy Operations**

In [57]:
arr=np.arange(0,10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [58]:
arr+5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [59]:
arr-5

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [60]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [61]:
arr/arr

<ipython-input-61-50b4ced5627e>:1: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [62]:
# Python program to demonstrate
# basic operations on single array
import numpy as np

a = np.array([1, 2, 5, 3])

# add 1 to every element
print ("Adding 1 to every element:", a+1)

# subtract 3 from each element
print ("Subtracting 3 from each element:", a-3)

# multiply each element by 10
print ("Multiplying each element by 10:", a*10)

# square each element
print ("Squaring each element:", a**2)

# modify existing array
a *= 2
print ("Doubled each element of original array:", a)

# transpose of array
a = np.array([[1, 2, 3], [3, 4, 5], [9, 6, 0]])

print ("\nOriginal array:\n", a)
print ("Transpose of array:\n", a.T)


Adding 1 to every element: [2 3 6 4]
Subtracting 3 from each element: [-2 -1  2  0]
Multiplying each element by 10: [10 20 50 30]
Squaring each element: [ 1  4 25  9]
Doubled each element of original array: [ 2  4 10  6]

Original array:
 [[1 2 3]
 [3 4 5]
 [9 6 0]]
Transpose of array:
 [[1 3 9]
 [2 4 6]
 [3 5 0]]


In [63]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [64]:
print("sin", np.sin(arr))
print("log", np.log(arr))
print("sum", np.sum(arr))
print("mean", np.mean(arr))
print("max", np.max(arr))
print("min", np.min(arr))

print("std", np.std(arr))



sin [ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849]
log [      -inf 0.         0.69314718 1.09861229 1.38629436 1.60943791
 1.79175947 1.94591015 2.07944154 2.19722458]
sum 45
mean 4.5
max 9
min 0
std 2.8722813232690143


<ipython-input-64-ed4c065786d3>:2: RuntimeWarning: divide by zero encountered in log
  print("log", np.log(arr))


**https://numpy.org/**

In [65]:
# Python program to demonstrate
# unary operators in numpy
import numpy as np

arr = np.array([[1, 5, 6],
				[4, 7, 2],
				[3, 1, 9]])

# maximum element of array
print ("Largest element is:", arr.max())
print ("Row-wise maximum elements:",
					arr.max(axis = 1))

# minimum element of array
print ("Column-wise minimum elements:",
						arr.min(axis = 0))

# sum of array elements
print ("Sum of all array elements:",
							arr.sum())

# cumulative sum along each row
print ("Cumulative sum along each row:\n",
						arr.cumsum(axis = 1))


Largest element is: 9
Row-wise maximum elements: [6 7 9]
Column-wise minimum elements: [1 1 2]
Sum of all array elements: 38
Cumulative sum along each row:
 [[ 1  6 12]
 [ 4 11 13]
 [ 3  4 13]]


Numpy operations on 2D Array

In [66]:
import numpy as np
arr=np.arange(0,9).reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [67]:
arr.sum(axis=1)# it means sum will take place across rows so column values will be added.

array([ 3, 12, 21])

In [68]:
arr = np.arange(9).reshape(3,3)
arr



array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [69]:
# Solution
arr[:, [0,1,2]]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

**Iterating Arrays**

In [70]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
for i in a:
    print(i)


1
2
3
4
5


In [71]:
# Iterating 2D Arrays

import numpy as np

b = np.array([[1, 2, 3], [4, 5, 6]])
for i in b:
    for j in i:
        print(j)


1
2
3
4
5
6


In [72]:
# Iterating 3D Arrays:

import numpy as np

c = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
for i in c:
    for j in i:
        for k in j:
            print(k)


1
2
3
4
5
6
7
8


In [73]:
# Iterating Arrays Using ndenumerate()
#The ndenumerate() function returns both the indices and the values of each element in the array.
#Here's an example:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
for i, j in np.ndenumerate(a):
    print(i, j)


(0,) 1
(1,) 2
(2,) 3
(3,) 4
(4,) 5


NumPy, a library for numerical computing in Python, provides several functions for searching, sorting and filtering arrays.

**numpy.searchsorted** This method is used to perform binary search on a sorted array. It returns the indices of the array where the specified values can be inserted to maintain the sorted order.

**searchsorted with "side"** parameter set to "right": This option allows the search to be performed starting from the right side of the array, rather than the default left side.

**Searching for multiple values:** You can use the numpy.isin method to check if multiple values are present in an array.

**Sorting arrays:** You can use the numpy.sort method to sort arrays in ascending or descending order.

**Sorting 2D arrays:** You can sort a 2D array based on the values in a specific column using the numpy.argsort method.

**Filtering arrays:** You can use boolean indexing to filter arrays based on certain conditions. For example, you can extract all elements from an array that are greater than a certain value.

**Creating filter arrays:** You can create a filter array with the same shape as the original array, where each element indicates whether the corresponding element in the original array satisfies a certain condition.

**Creating filters directly from arrays:** You can use the numpy.where method to create a filter directly from an array, based on a specified condition. The method returns the indices of the elements in the array that satisfy the condition.

In [ ]:
The searchsorted() method in NumPy is a
function that can be used to search for the
index at which a given value would be inserted into a
sorted array to maintain the sorted order.

numpy.searchsorted(a, v, side='left', sorter=None)


In [74]:
import numpy as np

a = np.array([1, 3, 4, 4, 4, 6, 8])

index = np.searchsorted(a, 4)

print(index)  # Output: 2


2


In this example, the **searchsorted()** method returns the index of the first occurrence of 4 in the sorted array a, which is 2.

The **in1d()** method in NumPy is a function that can be used to determine whether each element of a given set of values is present in a given input array. It returns a Boolean array indicating whether each value in the set of values is present in the input array.

Here is the syntax for using in1d():

***numpy.in1d(ar1, ar2, assume_unique=False, invert=False)***


where ar1 is the input array, ar2 is the set of values to be searched for, assume_unique is an optional parameter that specifies whether to assume that the input arrays are unique, and invert is an optional parameter that specifies whether to invert the output. If invert is set to True, the function returns a Boolean array indicating whether each value in the set of values is not present in the input array.

In [76]:
import numpy as np

ar1 = np.array([1, 2, 3, 4, 5])
ar2 = np.array([2, 4, 6])

result = np.in1d(ar1, ar2)

print(result)  # Output: [False  True False  True False]


[False  True False  True False]


**sort()**The sort() method is used to sort an array in-place. It modifies the input array and returns None. The syntax is as follows:

In [ ]:
numpy.sort(a, axis=-1, kind='quicksort', order=None)


where a is the input array, axis is an optional parameter that specifies the axis along which to sort the array, kind is an optional parameter that specifies the sorting algorithm to be used, and order is an optional parameter that specifies the order of sorting for multi-dimensional arrays.

In [77]:
import numpy as np

a = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5, 3, 5])

print(np.sort(a))

  # Output: [1 1 2 3 3 4 5 5 5 6 9]


[1 1 2 3 3 4 5 5 5 6 9]


**argsort():** The argsort() method is used to get the indices of the sorted elements in an array.

 It returns an array of indices that can be used to index the input array to get the sorted array.
  
 The syntax is as follows:

In [ ]:
numpy.argsort(a, axis=-1, kind='quicksort', order=None)


where a is the input array, axis is an optional parameter that specifies the axis along which to sort the array, kind is an optional parameter that specifies the sorting algorithm to be used, and order is an optional parameter that specifies the order of sorting for multi-dimensional arrays.

For example:

In [78]:
import numpy as np

a = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5, 3, 5])

index = np.argsort(a)

print(index)  # Output: [1 3 6 7 8 9 2 0 4 5 10]


[ 1  3  6  0  9  2  4  8 10  7  5]


**lexsort():** The lexsort() method is used to perform lexicographic sorting on multiple arrays. It returns an array of indices that can be used to index the input arrays to get the sorted arrays. The syntax is as follows:

In [ ]:
numpy.lexsort(keys, axis=-1)


where keys is a tuple of arrays to be sorted and axis is an optional parameter that specifies the axis along which to sort the arrays.

In [ ]:
import numpy as np

first_name = np.array(['John', 'Jane', 'Jim', 'Jerry', 'Joan'])
last_name = np.array(['Doe', 'Doe', 'Smith', 'Jones', 'Johnson'])

index = np.lexsort((last_name, first_name))

print(first_name[index])  # Output: ['Jim' 'Joan' 'Jane' 'Jerry' 'John']
print(last_name[index])   # Output: ['Smith' 'Johnson' 'Doe' 'Jones' 'Doe']


['Jane' 'Jerry' 'Jim' 'Joan' 'John']
['Doe' 'Jones' 'Smith' 'Johnson' 'Doe']


**filters directly from arrays**

In [ ]:
import numpy as np

a = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5, 3, 5])
b = np.array([2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

filter = a > b

print(a[filter])  # Output: [3 5 9 6]


[3 9]


In [ ]:
import numpy as np

a = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5, 3, 5])

filter = (a > 2) & (a < 9)

print(a[filter])  # Output: [3 4 5 5 6]


[3 4 5 6 5 3 5]


**"ufunc"** stands for Universal Functions. A ufunc is a function that performs element-wise operations on arrays, which means it operates on individual elements of an array rather than the entire array.

**NumPy ufuncs are vectorized operations**, which means they can be applied to arrays without using a for loop. This allows for efficient processing of large arrays and is a key feature of NumPy.

Some of the most commonly used NumPy ufuncs include:


*   np.add: element-wise addition
*   np.add: element-wise addition

*   np.multiply: element-wise multiplication
*   np.divide: element-wise division

*   np.power: element-wise power
*   np.exp: element-wise exponential

*   np.log: element-wise natural logarithm




In [ ]:
import numpy as np

a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])
c = np.add(a, b)
print(c)


[11 22 33 44]


In [ ]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
b = np.square(a)
print(b)


[ 1  4  9 16 25]


**To create your own ufunc in NumPy**, you can use the *numpy.vectorize* function.

`numpy.vectorize` is a decorator that takes a scalar function and returns a new function that applies the scalar function to arrays element-wise.

In [ ]:
import numpy as np

def my_func(x):
    return x**2 + 1

vec_my_func = np.vectorize(my_func)

a = np.array([1, 2, 3, 4])
b = vec_my_func(a)
print(b)


[ 2  5 10 17]


create your own NumPy ufunc, you need to write a function in Python  and then use NumPy's numpy.frompyfunc function to convert it into a ufunc.

In [ ]:
import numpy as np

def my_square(x):
    return x**2

my_ufunc = np.frompyfunc(my_square, 1, 1)

a = np.array([1, 2, 3, 4])
b = my_ufunc(a)
print(b)


[1 4 9 16]


In [ ]:
import numpy as np

def hypotenuse(x, y):
    return np.sqrt(x**2 + y**2)

hypotenuse_ufunc = np.frompyfunc(hypotenuse, 2, 1)
a = np.array([1, 2, 3, 4])
b = np.array([1,2,3,4])
c = hypotenuse_ufunc(a,b)
print(c)

[1.4142135623730951 2.8284271247461903 4.242640687119285 5.656854249492381]


To check if a function is a NumPy ufunc, you can use the numpy.ufunc class.

In [ ]:
import numpy as np

a = np.add

if isinstance(a, np.ufunc):
    print("a is a NumPy ufunc")
else:
    print("a is not a NumPy ufunc")


a is a NumPy ufunc


**The least common multiple (LCM)** of two numbers is the smallest number that is a multiple of both of the numbers. To find the LCM of two numbers, you can use the math.gcd function from the math module to calculate the greatest common divisor (GCD) of the two numbers, and then divide the product of the numbers by the GCD.

Here's an example of finding the LCM of two numbers:

In [ ]:
import math

def lcm(x, y):
    return x * y // math.gcd(x, y)

x = 15
y = 20

print(lcm(x, y))


60


In [ ]:
import numpy as np
import math

def lcm(a, b):
    return a * b // math.gcd(a, b)

lcm_ufunc = np.frompyfunc(lcm, 2, 1)

a = np.array([3, 4, 5])
b = np.array([6, 8, 10])
c = lcm_ufunc(a, b).astype(np.int64)
print(c)


[ 6  8 10]


To find the LCM of elements in an array, you can use the NumPy ufunc to apply the lcm function to all pairs of elements in the array. For example:

In [ ]:
import numpy as np
import math

def lcm(x, y):
    return x * y // math.gcd(x, y)

a = np.array([15, 20, 25, 30])
lcm_ufunc = np.frompyfunc(lcm, 2, 1)

b = lcm_ufunc.reduce(a)
print(b)


300


lcm_ufunc is created from the lcm function, and the reduce method is used to apply the lcm_ufunc to all pairs of elements in the array a. The resulting LCM is stored in the b array.

**The Greatest Common Divisor (GCD)** of two or more numbers is the largest positive integer that divides all the numbers without a remainder.

In NumPy, you can calculate the GCD of arrays using a custom ufunc.

In [ ]:
import numpy as np
import math

def gcd(a, b):
    while b:
        a, b = b, a % b
    return a

c=gcd(4,8)
print("GCD IS:  ", c)

GCD IS:   4


In [ ]:
import numpy as np
import math

def gcd(a, b):
    while b:
        a, b = b, a % b
    return a

gcd_ufunc = np.frompyfunc(gcd, 2, 1)

a = np.array([3, 4, 5])
b = np.array([6, 8, 10])
c = gcd_ufunc(a, b).astype(np.int64)
print(c)


[3 4 5]


A **set** is an unordered collection of unique elements. In mathematics, sets are used to represent a collection of distinct objects.


**In programming, sets** are used to store and manipulate collections of values.

In [ ]:
import numpy as np

a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3])
b = np.array([4, 5, 6, 7, 8, 9, 10, 11, 12])

set_a = np.unique(a)
set_b = np.unique(b)

print(set_a)
print(set_b)


[1 2 3 4 5 6 7 8 9]
[ 4  5  6  7  8  9 10 11 12]


**Union**

In [ ]:
import numpy as np

a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3])
b = np.array([4, 5, 6, 7, 8, 9, 10, 11, 12])

set_a = np.unique(a)
set_b = np.unique(b)

union = np.union1d(set_a, set_b)
print(union)


[ 1  2  3  4  5  6  7  8  9 10 11 12]


**Intersection**

In [ ]:
import numpy as np

a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3])
b = np.array([4, 5, 6, 7, 8, 9, 10, 11, 12])

set_a = np.unique(a)
set_b = np.unique(b)

intersection = np.intersect1d(set_a, set_b)
print(intersection)


**Difference**

In [ ]:
import numpy as np

a = np.array([3, 4, 4, 5, 5, 5])
b = np.array([5, 6, 7, 8, 8, 9])
set_a = np.unique(a)
set_b = np.unique(b)
difference = np.setdiff1d(set_a, set_b)
print(difference)


[3 4]


The **symmetric difference** of two sets is the set of all elements that belong to exactly one of the sets.

In [ ]:
import numpy as np

a = np.array([3, 4, 4, 5, 5, 5])
b = np.array([5, 6, 7, 8, 8, 9])
set_a = np.unique(a)
set_b = np.unique(b)
symmetric_difference = np.setxor1d(set_a, set_b)
print(symmetric_difference)


[3 4 6 7 8 9]
